[package]
name = "renegade-price-reporter"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Networking === #
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-tungstenite = { version = "0.18", features = ["native-tls"]}
tungstenite = "0.18"
hyper = { version = "0.14", features = ["http1", "http2", "server", "tcp"] }
matchit = "0.7"

# === Runtime === #
tokio = "1"
async-trait = "0.1"
futures-util = "0.3"

# === Serde === #
serde = "1"
serde_json = "1"

# === Telemetry === #
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"]}

# === Renegade === #
price-reporter = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }
external-api = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }
arbitrum-client = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }
config = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }
common = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }
util = { git = "https://github.com/renegade-fi/renegade.git", branch = "dev" }

