[workspace]
members = [
    "auth/auth-server",
    "auth/auth-server-api",
    "compliance/compliance-server",
    "compliance/compliance-api",
    "dealer/renegade-dealer",
    "dealer/renegade-dealer-api",
    "funds-manager/funds-manager-api",
    "funds-manager/funds-manager-server",
    "price-reporter",
]

[profile.bench]
opt-level = 3
lto = true
debug = true

[profile.release]
opt-level = 3 # Full optimizations
lto = true

[workspace.dependencies]
# === Renegade Dependencies === #
renegade-arbitrum-client = { package = "arbitrum-client", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping", features = [
    "rand",
] }
renegade-api = { package = "external-api", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-common = { package = "common", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-config = { package = "config", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-constants = { package = "constants", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-circuits = { package = "circuits", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-circuit-types = { package = "circuit-types", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-crypto = { git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-util = { package = "util", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }
renegade-price-reporter = { package = "price-reporter", git = "https://github.com/renegade-fi/renegade.git", branch = "andrew/new-token-mapping" }

# === Database Dependencies === #
diesel = { version = "2.1" }
diesel-async = { version = "0.4" }

# === Misc Dependencies === #
tracing = "0.1"
