[workspace]
members = [
    "dealer/renegade-dealer",
    "dealer/renegade-dealer-api",
    "fee-sweeper",
    "price-reporter",
]

[profile.bench]
opt-level = 3
lto = true
debug = true

[profile.release]
opt-level = 3 # Full optimizations
lto = true
