[package]
name = "auth-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# === HTTP Server === #
clap = { version = "4.0", features = ["derive", "env"] }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"

# === Database === #
bb8 = "0.8"
diesel = { version = "2", features = ["postgres", "chrono", "uuid"] }
diesel-async = { version = "0.4", features = ["postgres", "bb8"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = "0.2"

# === Cryptography === #
aes-gcm = "0.10.1"
rand = "0.8.5"

# === Renegade Dependencies === #
auth-server-api = { path = "../auth-server-api" }
renegade-circuit-types = { package = "circuit-types", git = "https://github.com/renegade-fi/renegade.git" }
renegade-common = { package = "common", git = "https://github.com/renegade-fi/renegade.git" }
renegade-metrics = { package = "renegade-metrics", git = "https://github.com/renegade-fi/renegade.git" }
renegade-util = { package = "util", git = "https://github.com/renegade-fi/renegade.git" }
renegade-api = { package = "external-api", git = "https://github.com/renegade-fi/renegade.git", features = [
    "auth",
] }
renegade-crypto = { git = "https://github.com/renegade-fi/renegade.git" }

# === Misc Dependencies === #
base64 = "0.22.1"
bytes = "1.0"
cached = "0.53"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
metrics = "=0.22.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.0", features = ["serde", "v4"] }
