[package]
name = "funds-manager-api"
version = "0.1.0"
edition = "2021"

[dependencies]

renegade-api = { package = "external-api", workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
